---
version: "3"
services:
  core:
    image: yuzutech/kroki:${KROKI_CONTAINER_IMAGE_TAG:-latest}
    depends_on:
      - bpmn
      - excalidraw
      - mermaid
    environment:
      - KROKI_BPMN_HOST=bpmn
      - KROKI_DIAGRAMSNET_HOST=diagramsnet
      - KROKI_EXCALIDRAW_HOST=excalidraw
      - KROKI_MERMAID_HOST=mermaid
      # Enable inclusion of, for instance, external PlantUML descriptions and
      # Vega datasets
      - KROKI_SAFE_MODE=unsafe
    ports:
      - 8000:8000
  bpmn:
    image: yuzutech/kroki-bpmn:${KROKI_CONTAINER_IMAGE_TAG:-latest}
  diagramsnet:
    image: yuzutech/kroki-diagramsnet:${KROKI_CONTAINER_IMAGE_TAG:-latest}
  excalidraw:
    image: yuzutech/kroki-excalidraw:${KROKI_CONTAINER_IMAGE_TAG:-latest}
  mermaid:
    image: yuzutech/kroki-mermaid:${KROKI_CONTAINER_IMAGE_TAG:-latest}
