name = "Kroki"
uuid = "b3565e16-c1f2-4fe9-b4ab-221c88942068"
authors = ["Joris Kraak <me@joriskraak.nl>"]
version = "1.0.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
CodecZlib = "0.7"
# `DocStringExtensions is a development dependency, so its compatibility range
# is wider to not restrict dependents of this package in their dependency on
# `DocStringExtensions`
DocStringExtensions = "0.8, 0.9"
# The wider compatibility range for `HTTP` ensures compatibility with
# up-to-date versions of `Pluto`, etc.
HTTP = "0.8, 0.9, 1"
JSON = "0.21.3"
Reexport = "1.2.2"
julia = "1.6"
